use crate::wasm_stream::pipeline::StreamPass;
use eyre::Result;
use wasm_encoder::{ExportSection, ImportSection, Module, Section, EntityType};
use wasmparser::Parser;
use strum::VariantNames;
use crate::{
    abi::Wasip1ABIFunc,
    unique_name::UniqueName,
    util::gen_component_name,
};

/// Apply the patch to use wit-bindgen.
/// As it will be rejected otherwise,
/// swap the import function generated by wit with the wasip1 import function.
pub struct PatchComponentStreamPass;

impl PatchComponentStreamPass {
    pub fn new() -> Self {
        Self
    }
}

impl StreamPass for PatchComponentStreamPass {
    fn run(&mut self, input_wasm: &[u8]) -> Result<Vec<u8>> {
        let mut module = Module::new();
        let parser = Parser::new(0);

        let mut replacements = std::collections::HashMap::new();
        let mut anchors_to_remove = std::collections::HashSet::new();

        for (name, (namespace, root)) in
            <Wasip1ABIFunc as VariantNames>::VARIANTS
                .iter()
                .zip(core::iter::repeat((
                    UniqueName::WASIP1_ABI_MODULE_ALT,
                    UniqueName::CORE_MODULE_ROOT,
                )))
        {
            let component_name = gen_component_name(namespace, name);
            replacements.insert((root.to_string(), component_name), (UniqueName::WASIP1_ABI_MODULE.to_string(), name.to_string()));
            anchors_to_remove.insert(format!("{name}_import_anchor"));
        }

        for payload in parser.parse_all(input_wasm) {
            let payload = payload?;
            let section_info = payload.as_section().map(|(id, r)| (id, r.clone()));
            
            match payload {
                wasmparser::Payload::ImportSection(s) => {
                    let mut new_import_section = ImportSection::new();
                    for import_group in s {
                        for import_res in import_group.unwrap() {
                            let (_, import) = import_res.unwrap();
                            let entity_type = match import.ty {
                                wasmparser::TypeRef::Func(f) => EntityType::Function(f),
                                wasmparser::TypeRef::Table(t) => EntityType::Table(crate::wasm_stream::translator::translate_table_type(t, &crate::wasm_stream::translator::DefaultRebinder)),
                                wasmparser::TypeRef::Memory(m) => EntityType::Memory(crate::wasm_stream::translator::translate_memory_type(m)),
                                wasmparser::TypeRef::Global(g) => EntityType::Global(crate::wasm_stream::translator::translate_global_type(g, &crate::wasm_stream::translator::DefaultRebinder)),
                                wasmparser::TypeRef::Tag(t) => EntityType::Tag(crate::wasm_stream::translator::translate_tag_type(t)),
                                _ => unimplemented!("TypeRef variant not supported"),
                            };

                            let (new_module, new_name) = replacements.get(&(import.module.to_string(), import.name.to_string()))
                                .map(|(m, n)| (m.as_str(), n.as_str()))
                                .unwrap_or((import.module, import.name));
                                
                            new_import_section.import(new_module, new_name, entity_type);
                        }
                    }
                    module.section(&new_import_section);
                }
                wasmparser::Payload::ExportSection(s) => {
                    let mut new_export_section = ExportSection::new();
                    for export in s {
                        let export = export?;
                        if !anchors_to_remove.contains(export.name) {
                            let export_kind = match export.kind {
                                wasmparser::ExternalKind::Func => wasm_encoder::ExportKind::Func,
                                wasmparser::ExternalKind::Table => wasm_encoder::ExportKind::Table,
                                wasmparser::ExternalKind::Memory => wasm_encoder::ExportKind::Memory,
                                wasmparser::ExternalKind::Global => wasm_encoder::ExportKind::Global,
                                wasmparser::ExternalKind::Tag => wasm_encoder::ExportKind::Tag,
                                _ => unimplemented!("ExternalKind variant not supported"),
                            };
                            new_export_section.export(export.name, export_kind, export.index);
                        }
                    }
                    module.section(&new_export_section);
                }
                _ => {
                    if let Some((id, range)) = section_info {
                        module.section(&wasm_encoder::RawSection {
                            id,
                            data: &input_wasm[range.clone()],
                        });
                    }
                }
            }
        }
        
        Ok(module.finish())
    }
}
