[workspace]
members = [
    "wasi_virt_layer-cli",
    "wasi_virt_layer",
    "examples/bare/ls",
    "examples/bare/ls2",
    "examples/vfs/example",
    "examples/dynamic",
    "examples/test_wasm/example",
    "examples/test_wasm/test_args",
    "examples/vfs/rustc_vfs",
    "examples/vfs/thread_direct_vfs",
    "examples/test_wasm/test_threads",
    "examples/vfs/threads_vfs",
    "examples/vfs/anonymous_threads_vfs",
    "examples/test_wasm/test_pool_thread",
    "examples/vfs/thread_pool_vfs",
    "examples/vfs/no_std_vfs",
    "examples/vfs/no_thread_with_thread_feature_vfs",
    "examples/vfs/spawn_vfs_and_body_vfs",
    "examples/test_wasm/spawn_vfs_and_body_example",
    "examples/bare/ls-vfs",
    "examples/bare/args",
    "examples/bare/args-vfs",
    "examples/threads/ls-threads",
    "examples/threads/ls-threads-vfs",
    "examples/multiple-vfs",
    "test_new_bare",
    "examples/bare/tree",
    "examples/dynamic-wasm",
    "examples/dynamic-wasm-multiple",
    "examples/bare/self-rw-vfs",
    "examples/threads/self-rw-vfs",
    "examples/threads/complex-threads-vfs",
    "examples/threads/pool-threads-vfs",
    "examples/test_wasm/self_rw_example",
    "examples/vfs/self-vfs",
    "examples/vfs/test_helper_vfs",
    "examples/vfs/test_helper_shared_memory_vfs",
    "examples/bare/test-unreachable",
    "examples/test_wasm/test_unreachable_target",
    "examples/vfs/unreachable_threads_vfs",
    "examples/test_wasm/unreachable_threads_target",
    "examples/bare/test-unreachable-target1",
    "examples/bare/test-unreachable-target2",
    "examples/vfs/unreachable-multi-target-vfs",
    "examples/multi-location-vfs",
    "examples/mock-targets/location-1",
    "examples/mock-targets/location-1/subdir",
    "examples/mock-targets/location-2",
    "examples/mock-targets/location-2/subdir",
    "examples/vfs/repro_multi_target_table_bug",
    "examples/vfs/minimal_repro",
    "examples/vfs/minimal_repro_virtual",
    "examples/vfs/dynamic_args_vfs",
    "examples/vfs/lfs_api_test_vfs",
    "examples/vfs/vfs_host_test_vfs",
    "examples/test_wasm/vfs_host_test_target",
    "examples/test_wasm/test_poll",
    "examples/vfs/wait_poll_vfs",
    "examples/test_wasm/test_atomic_wait",
    "examples/vfs/atomic_wait_vfs",
    "examples/test_wasm/test_mkdir",
    "examples/vfs/mkdir_vfs",
]
resolver = "2"
default-members = ["wasi_virt_layer", "wasi_virt_layer-cli"]

[workspace.package]
authors = ["oligami <nziq53@gmail.com>"]
version = "0.4.6"
edition = "2024"
description = ""
rust-version = "1.89.0"
keywords = []
repository = ""
documentation = ""
homepage = ""
readme = "README.md"

[workspace.dependencies]
wasi_virt_layer = { path = "wasi_virt_layer", default-features = false }

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

[workspace.metadata.release]
tag-name = "v{{version}}"
shared-version = true
