use strum::{VariantNames, EnumString, EnumIter, EnumMessage};
#[derive(strum_macros::EnumString, strum_macros::EnumIter, Clone, Copy, Debug, PartialEq, Eq, strum_macros::Display, Hash, strum_macros::EnumMessage, strum_macros::VariantNames)]
#[strum(serialize_all = "snake_case")]
pub enum Wasip1ABIFunc {
    ArgsGet,
    ArgsSizesGet,
    EnvironGet,
    EnvironSizesGet,
    ClockResGet,
    ClockTimeGet,
    FdAdvise,
    FdAllocate,
    FdClose,
    FdDatasync,
    FdFdstatGet,
    FdFdstatSetFlags,
    FdFdstatSetRights,
    FdFilestatGet,
    FdFilestatSetSize,
    FdFilestatSetTimes,
    FdPread,
    FdPrestatGet,
    FdPrestatDirName,
    FdPwrite,
    FdRead,
    FdReaddir,
    FdRenumber,
    FdSeek,
    FdSync,
    FdTell,
    FdWrite,
    PathCreateDirectory,
    PathFilestatGet,
    PathFilestatSetTimes,
    PathLink,
    PathOpen,
    PathReadlink,
    PathRemoveDirectory,
    PathRename,
    PathSymlink,
    PathUnlinkFile,
    PollOneoff,
    ProcExit,
    SchedYield,
    RandomGet,
    SockAccept,
    SockRecv,
    SockSend,
    SockShutdown,
}
fn main() {
    println!("{:?}", <Wasip1ABIFunc as VariantNames>::VARIANTS);
}
