[package]
name = "wasip1-virtual-layer"
version = "0.1.0"
edition = "2024"

[dependencies]
wit-bindgen = { version = "0.41.0", default-features = false }
wasip1 = { version = "0.11.0", default-features = false, package = "wasi" }
const_struct = "0.5.3"
const_for = "0.1.5"
