[package]
name = "ls-vfs"
authors.workspace = true
version.workspace = true
edition.workspace = true
description.workspace = true
rust-version.workspace = true
keywords.workspace = true
repository.workspace = true
documentation.workspace = true
homepage.workspace = true
readme.workspace = true

[dependencies]
const_struct = "0.6.4"
wit-bindgen = { version = "0.54.0", default-features = false, features = [
    "macros",
    "std",
] }

[dependencies.wasi_virt_layer]
# version = "0.1.5"
workspace = true
features = [
    # "trace-fs"
    # "std",
    "const-fs",
    "multiple-fs",
]

[lib]
crate-type = ["cdylib"]
