[package]
name = "ls-vfs"
authors.workspace = true
version.workspace = true
edition.workspace = true
description.workspace = true
rust-version.workspace = true
keywords.workspace = true
repository.workspace = true
documentation.workspace = true
homepage.workspace = true
readme.workspace = true

[dependencies]
const_struct = "0.6.2"
wit-bindgen = "0.54.0"

[dependencies.wasi_virt_layer]
# version = "*"
workspace = true
features = [
    # "trace-fs"
    # "std",
]

[lib]
crate-type = ["cdylib"]
