//! Generate TypeScript helper code for VFS modules.
//!
//! Two distinct VFS modes generate fundamentally different helpers:
//!
//! **PseudoWasm Mode**: VFS manages targets internally
//! - Generates a registration utility function only
//! - Targets are managed by VFS, not by TS code
//! - Function: `registerPseudoWasmTarget(name, wasmBuffer) → Promise`
//!
//! **SharedMemory Mode**: Targets run in worker threads with shared memory
//! - Generates configuration structures for thread communication
//! - Contains: initialization config, memory info, metadata pointers
//! - Exported for use when setting up worker threads

use std::collections::HashSet;

/// Represents a VFS export function
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct VfsExport {
    /// Full export name (e.g., "__wasi_export_pseudo_wasm_MY_VFS")
    pub name: String,
    /// Type of VFS
    pub vfs_type: VfsType,
    /// Holder name (e.g., "MY_VFS")
    pub holder_name: String,
}

/// Type of VFS export
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum VfsType {
    /// Using export_pseudo_wasm! macro
    PseudoWasm,
    /// Using export_shared_memory_manager! macro (threads feature)
    SharedMemoryManager,
}

impl VfsType {
    /// Get string representation of this VFS type
    pub fn as_str(&self) -> &'static str {
        match self {
            VfsType::PseudoWasm => "pseudo_wasm",
            VfsType::SharedMemoryManager => "shared_memory_manager",
        }
    }
}

/// Detect VFS exports from module export list
pub fn detect_vfs_exports(export_names: &[&str]) -> Vec<VfsExport> {
    let mut exports = Vec::new();
    let mut seen_holders = HashSet::new();

    for name in export_names {
        if let Some(export) = parse_vfs_export(name) {
            if seen_holders.insert(export.holder_name.clone()) {
                exports.push(export);
            }
        }
    }

    exports
}

/// Parse single VFS export name
fn parse_vfs_export(export_name: &str) -> Option<VfsExport> {
    if !export_name.starts_with("__wasi_export_") {
        return None;
    }

    let remaining = &export_name["__wasi_export_".len()..];

    if remaining.starts_with("pseudo_wasm_") {
        let holder_name = remaining["pseudo_wasm_".len()..].to_string();
        return Some(VfsExport {
            name: export_name.to_string(),
            vfs_type: VfsType::PseudoWasm,
            holder_name,
        });
    }

    if remaining.starts_with("shared_memory_manager_") {
        let holder_name = remaining["shared_memory_manager_".len()..].to_string();
        return Some(VfsExport {
            name: export_name.to_string(),
            vfs_type: VfsType::SharedMemoryManager,
            holder_name,
        });
    }

    None
}

/// Generate TypeScript helper for VFS
pub fn generate_ts_helper(
    vfs_name: &str,
    vfs_exports: &[VfsExport],
    target_names: &[&str],
) -> String {
    if vfs_exports.is_empty() {
        return generate_minimal_helper(vfs_name, target_names);
    }

    let vfs_export = &vfs_exports[0];

    match vfs_export.vfs_type {
        VfsType::PseudoWasm => generate_pseudo_wasm_helper(vfs_name),
        VfsType::SharedMemoryManager => generate_shared_memory_helper(vfs_name, target_names),
    }
}

/// Generate helper for PseudoWasm (VFS-managed targets)
fn generate_pseudo_wasm_helper(vfs_name: &str) -> String {
    format!(
        r#"/**
 * PseudoWasm Helper for {vfs_name}
 * 
 * Provides utility to register Wasip1 targets with the VFS.
 * The VFS internally manages all target execution.
 */

/**
 * Register a target module with the VFS
 * @param targetName - Unique name for this target
 * @param wasmBuffer - Compiled Wasip1 WASM module as ArrayBuffer
 */
export async function registerPseudoWasmTarget(
  targetName: string,
  wasmBuffer: ArrayBuffer
): Promise<void> {{
  const vfs = await import('./{vfs_name}.js');
  // Call VFS's target registration function
  // The actual binding is generated by export_pseudo_wasm! macro
  if (vfs.registerTarget) {{
    return vfs.registerTarget(targetName, wasmBuffer);
  }}
  throw new Error('VFS does not export registerTarget function');
}}
"#,
        vfs_name = vfs_name,
    )
}

/// Generate helper for SharedMemory (worker thread shared memory)
fn generate_shared_memory_helper(vfs_name: &str, _target_names: &[&str]) -> String {
    format!(
        r#"/**
 * SharedMemory Helper for {vfs_name}
 * 
 * Provides configuration and setup for worker threads using shared memory.
 * The generated config is passed to worker threads for zero-copy coordination.
 */

/**
 * Initialization config for worker thread
 * Contains VFS memory info and metadata pointers
 */
export interface SharedMemoryWorkerConfig {{
  /** Shared WebAssembly.Memory instance */
  memory: WebAssembly.Memory;
  /** VFS WASM module buffer */
  vfsWasmBuffer: ArrayBuffer;
  /** Target WASM module buffer */
  targetWasmBuffer: ArrayBuffer;
  /** Pointer to target metadata (returned by registration ABI) */
  metadataPtr: number;
}}

/**
 * Create configuration for passing to worker thread
 * @param vfsBuffer - VFS WASM module as ArrayBuffer
 * @param targetBuffer - Target WASM module as ArrayBuffer
 * @param memory - Shared memory instance from VFS
 * @param metadataPtr - Metadata pointer from VFS registration ABI
 * @returns Configuration object for worker setup
 */
export function createSharedMemoryWorkerConfig(
  vfsBuffer: ArrayBuffer,
  targetBuffer: ArrayBuffer,
  memory: WebAssembly.Memory,
  metadataPtr: number
): SharedMemoryWorkerConfig {{
  return {{
    memory,
    vfsWasmBuffer: vfsBuffer,
    targetWasmBuffer: targetBuffer,
    metadataPtr,
  }};
}}

/**
 * Initialize target in worker thread with shared memory
 * @param config - Worker config from createSharedMemoryWorkerConfig
 * @returns Target instance sharing memory with VFS
 */
export async function initializeSharedMemoryTarget(
  config: SharedMemoryWorkerConfig
): Promise<WebAssembly.Instance> {{
  const {{ memory, targetWasmBuffer }} = config;
  
  // Target imports shared memory from VFS
  const imports: WebAssembly.Imports = {{
    env: {{
      memory,
    }},
  }};
  
  const module = await WebAssembly.instantiate(targetWasmBuffer, imports);
  return module.instance;
}}
"#,
        vfs_name = vfs_name,
    )
}

/// Generate minimal helper when no VFS exports detected
fn generate_minimal_helper(vfs_name: &str, _target_names: &[&str]) -> String {
    format!(
        r#"/**
 * Minimal Helper for {vfs_name}
 * 
 * No VFS exports detected. Provide your own module loading/coordination.
 */

export async function loadVfsModule(wasmPath: string): Promise<WebAssembly.Instance> {{
  const response = await fetch(wasmPath);
  const buffer = await response.arrayBuffer();
  const module = await WebAssembly.instantiate(buffer);
  return module.instance;
}}
"#,
        vfs_name = vfs_name,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_pseudo_wasm_export() {
        let export = parse_vfs_export("__wasi_export_pseudo_wasm_MY_VFS");
        assert!(export.is_some());
        let export = export.unwrap();
        assert_eq!(export.vfs_type, VfsType::PseudoWasm);
        assert_eq!(export.holder_name, "MY_VFS");
    }

    #[test]
    fn test_parse_shared_memory_export() {
        let export = parse_vfs_export("__wasi_export_shared_memory_manager_THREADS_VFS");
        assert!(export.is_some());
        let export = export.unwrap();
        assert_eq!(export.vfs_type, VfsType::SharedMemoryManager);
        assert_eq!(export.holder_name, "THREADS_VFS");
    }

    #[test]
    fn test_detect_vfs_exports() {
        let exports = vec![
            "__wasi_export_pseudo_wasm_VFS1",
            "__wasi_export_shared_memory_manager_VFS2",
            "other_export",
        ];
        
        let detected = detect_vfs_exports(&exports.iter().map(|s| *s).collect::<Vec<_>>());
        assert_eq!(detected.len(), 2);
        assert_eq!(detected[0].vfs_type, VfsType::PseudoWasm);
        assert_eq!(detected[1].vfs_type, VfsType::SharedMemoryManager);
    }

    #[test]
    fn test_generate_pseudo_wasm() {
        let exports = vec![VfsExport {
            name: "__wasi_export_pseudo_wasm_MY_VFS".to_string(),
            vfs_type: VfsType::PseudoWasm,
            holder_name: "MY_VFS".to_string(),
        }];

        let helper = generate_ts_helper("my_vfs", &exports, &[]);

        assert!(helper.contains("registerPseudoWasmTarget"));
        assert!(helper.contains("targetName: string"));
        assert!(!helper.contains("SharedMemoryWorkerConfig"));
    }

    #[test]
    fn test_generate_shared_memory() {
        let exports = vec![VfsExport {
            name: "__wasi_export_shared_memory_manager_MY_VFS".to_string(),
            vfs_type: VfsType::SharedMemoryManager,
            holder_name: "MY_VFS".to_string(),
        }];

        let helper = generate_ts_helper("my_vfs", &exports, &["target1"]);

        assert!(helper.contains("SharedMemoryWorkerConfig"));
        assert!(helper.contains("createSharedMemoryWorkerConfig"));
        assert!(helper.contains("initializeSharedMemoryTarget"));
    }

    #[test]
    fn test_no_duplicate_exports() {
        let exports = vec![
            "__wasi_export_pseudo_wasm_VFS",
            "__wasi_export_pseudo_wasm_VFS",
            "__wasi_export_shared_memory_manager_VFS",
        ];
        
        let detected = detect_vfs_exports(&exports.iter().map(|s| *s).collect::<Vec<_>>());
        // Only 1 because both duplicates have same holder name
        // Holders: pseudo_wasm_VFS -> "VFS", shared_memory_manager_VFS -> "VFS" (same!)
        assert_eq!(detected.len(), 1);
        assert_eq!(detected[0].vfs_type, VfsType::PseudoWasm); // First one wins
    }
}
