// wit/virtual_file_system.wit
// wit is only kebab-case
package wasip1-vfs:host;

// wit-bindgen rust virtual-layer/wit --out-dir ./virtual-layer/src/wit/ -w virtual-file-system

world virtual-file-system {
  import virtual-file-system-wasip1-core;
}
