[package]
name = "pool-threads-vfs"
authors.workspace = true
version.workspace = true
edition.workspace = true
description.workspace = true
rust-version.workspace = true
keywords.workspace = true
repository.workspace = true
documentation.workspace = true
homepage.workspace = true
readme.workspace = true

[dependencies]
const_struct = "0.6.4"
parking_lot = "0.12.5"
wit-bindgen = { version = "0.54.0", default-features = false, features = [
    "macros",
    "std",
] }

[dependencies.wasi_virt_layer]
workspace = true
features = ["threads", "embedded-fs"]

[lib]
crate-type = ["cdylib"]
