pub fn memory_op_info<'a>(op: &wasmparser::Operator<'a>) -> Option<(u32, bool, wasm_encoder::ValType)> {
    match op {
        wasmparser::Operator::I32Load { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I32)),
        wasmparser::Operator::I64Load { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I64)),
        wasmparser::Operator::F32Load { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::F32)),
        wasmparser::Operator::F64Load { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::F64)),
        wasmparser::Operator::I32Load8S { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I32)),
        wasmparser::Operator::I32Load8U { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I32)),
        wasmparser::Operator::I32Load16S { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I32)),
        wasmparser::Operator::I32Load16U { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I32)),
        wasmparser::Operator::I64Load8S { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I64Load8U { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I64Load16S { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I64Load16U { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I64Load32S { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I64Load32U { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I32Store { memarg } => Some((memarg.memory, true, wasm_encoder::ValType::I32)),
        wasmparser::Operator::I64Store { memarg } => Some((memarg.memory, true, wasm_encoder::ValType::I64)),
        wasmparser::Operator::F32Store { memarg } => Some((memarg.memory, true, wasm_encoder::ValType::F32)),
        wasmparser::Operator::F64Store { memarg } => Some((memarg.memory, true, wasm_encoder::ValType::F64)),
        wasmparser::Operator::I32Store8 { memarg } => Some((memarg.memory, true, wasm_encoder::ValType::I32)),
        wasmparser::Operator::I32Store16 { memarg } => Some((memarg.memory, true, wasm_encoder::ValType::I32)),
        wasmparser::Operator::I64Store8 { memarg } => Some((memarg.memory, true, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I64Store16 { memarg } => Some((memarg.memory, true, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I64Store32 { memarg } => Some((memarg.memory, true, wasm_encoder::ValType::I64)),
        wasmparser::Operator::MemoryAtomicNotify { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I32)),
        wasmparser::Operator::MemoryAtomicWait32 { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I32)),
        wasmparser::Operator::MemoryAtomicWait64 { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I32AtomicLoad { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I32)),
        wasmparser::Operator::I64AtomicLoad { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I32AtomicLoad8U { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I32)),
        wasmparser::Operator::I32AtomicLoad16U { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I32)),
        wasmparser::Operator::I64AtomicLoad8U { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I64AtomicLoad16U { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I64AtomicLoad32U { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I32AtomicStore { memarg } => Some((memarg.memory, true, wasm_encoder::ValType::I32)),
        wasmparser::Operator::I64AtomicStore { memarg } => Some((memarg.memory, true, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I32AtomicStore8 { memarg } => Some((memarg.memory, true, wasm_encoder::ValType::I32)),
        wasmparser::Operator::I32AtomicStore16 { memarg } => Some((memarg.memory, true, wasm_encoder::ValType::I32)),
        wasmparser::Operator::I64AtomicStore8 { memarg } => Some((memarg.memory, true, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I64AtomicStore16 { memarg } => Some((memarg.memory, true, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I64AtomicStore32 { memarg } => Some((memarg.memory, true, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I32AtomicRmwAdd { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I32)),
        wasmparser::Operator::I64AtomicRmwAdd { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I32AtomicRmw8AddU { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I32)),
        wasmparser::Operator::I32AtomicRmw16AddU { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I32)),
        wasmparser::Operator::I64AtomicRmw8AddU { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I64AtomicRmw16AddU { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I64AtomicRmw32AddU { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I32AtomicRmwSub { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I32)),
        wasmparser::Operator::I64AtomicRmwSub { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I32AtomicRmw8SubU { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I32)),
        wasmparser::Operator::I32AtomicRmw16SubU { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I32)),
        wasmparser::Operator::I64AtomicRmw8SubU { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I64AtomicRmw16SubU { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I64AtomicRmw32SubU { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I32AtomicRmwAnd { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I32)),
        wasmparser::Operator::I64AtomicRmwAnd { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I32AtomicRmw8AndU { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I32)),
        wasmparser::Operator::I32AtomicRmw16AndU { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I32)),
        wasmparser::Operator::I64AtomicRmw8AndU { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I64AtomicRmw16AndU { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I64AtomicRmw32AndU { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I32AtomicRmwOr { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I32)),
        wasmparser::Operator::I64AtomicRmwOr { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I32AtomicRmw8OrU { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I32)),
        wasmparser::Operator::I32AtomicRmw16OrU { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I32)),
        wasmparser::Operator::I64AtomicRmw8OrU { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I64AtomicRmw16OrU { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I64AtomicRmw32OrU { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I32AtomicRmwXor { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I32)),
        wasmparser::Operator::I64AtomicRmwXor { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I32AtomicRmw8XorU { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I32)),
        wasmparser::Operator::I32AtomicRmw16XorU { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I32)),
        wasmparser::Operator::I64AtomicRmw8XorU { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I64AtomicRmw16XorU { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I64AtomicRmw32XorU { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I32AtomicRmwXchg { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I32)),
        wasmparser::Operator::I64AtomicRmwXchg { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I32AtomicRmw8XchgU { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I32)),
        wasmparser::Operator::I32AtomicRmw16XchgU { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I32)),
        wasmparser::Operator::I64AtomicRmw8XchgU { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I64AtomicRmw16XchgU { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I64AtomicRmw32XchgU { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I32AtomicRmwCmpxchg { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I32)),
        wasmparser::Operator::I64AtomicRmwCmpxchg { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I32AtomicRmw8CmpxchgU { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I32)),
        wasmparser::Operator::I32AtomicRmw16CmpxchgU { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I32)),
        wasmparser::Operator::I64AtomicRmw8CmpxchgU { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I64AtomicRmw16CmpxchgU { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I64)),
        wasmparser::Operator::I64AtomicRmw32CmpxchgU { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::I64)),
        wasmparser::Operator::V128Load { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::V128)),
        wasmparser::Operator::V128Load8x8S { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::V128)),
        wasmparser::Operator::V128Load8x8U { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::V128)),
        wasmparser::Operator::V128Load16x4S { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::V128)),
        wasmparser::Operator::V128Load16x4U { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::V128)),
        wasmparser::Operator::V128Load32x2S { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::V128)),
        wasmparser::Operator::V128Load32x2U { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::V128)),
        wasmparser::Operator::V128Load8Splat { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::V128)),
        wasmparser::Operator::V128Load16Splat { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::V128)),
        wasmparser::Operator::V128Load32Splat { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::V128)),
        wasmparser::Operator::V128Load64Splat { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::V128)),
        wasmparser::Operator::V128Load32Zero { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::V128)),
        wasmparser::Operator::V128Load64Zero { memarg } => Some((memarg.memory, false, wasm_encoder::ValType::V128)),
        wasmparser::Operator::V128Store { memarg } => Some((memarg.memory, true, wasm_encoder::ValType::V128)),
        _ => None,
    }
}

pub fn clear_memory_index(op: &mut wasm_encoder::Instruction) {
    match op {
        wasm_encoder::Instruction::I32Load(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64Load(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::F32Load(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::F64Load(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I32Load8S(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I32Load8U(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I32Load16S(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I32Load16U(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64Load8S(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64Load8U(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64Load16S(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64Load16U(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64Load32S(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64Load32U(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I32Store(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64Store(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::F32Store(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::F64Store(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I32Store8(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I32Store16(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64Store8(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64Store16(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64Store32(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::MemoryAtomicNotify(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::MemoryAtomicWait32(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::MemoryAtomicWait64(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I32AtomicLoad(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64AtomicLoad(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I32AtomicLoad8U(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I32AtomicLoad16U(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64AtomicLoad8U(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64AtomicLoad16U(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64AtomicLoad32U(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I32AtomicStore(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64AtomicStore(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I32AtomicStore8(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I32AtomicStore16(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64AtomicStore8(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64AtomicStore16(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64AtomicStore32(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I32AtomicRmwAdd(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64AtomicRmwAdd(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I32AtomicRmw8AddU(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I32AtomicRmw16AddU(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64AtomicRmw8AddU(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64AtomicRmw16AddU(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64AtomicRmw32AddU(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I32AtomicRmwSub(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64AtomicRmwSub(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I32AtomicRmw8SubU(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I32AtomicRmw16SubU(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64AtomicRmw8SubU(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64AtomicRmw16SubU(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64AtomicRmw32SubU(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I32AtomicRmwAnd(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64AtomicRmwAnd(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I32AtomicRmw8AndU(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I32AtomicRmw16AndU(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64AtomicRmw8AndU(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64AtomicRmw16AndU(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64AtomicRmw32AndU(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I32AtomicRmwOr(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64AtomicRmwOr(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I32AtomicRmw8OrU(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I32AtomicRmw16OrU(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64AtomicRmw8OrU(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64AtomicRmw16OrU(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64AtomicRmw32OrU(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I32AtomicRmwXor(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64AtomicRmwXor(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I32AtomicRmw8XorU(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I32AtomicRmw16XorU(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64AtomicRmw8XorU(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64AtomicRmw16XorU(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64AtomicRmw32XorU(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I32AtomicRmwXchg(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64AtomicRmwXchg(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I32AtomicRmw8XchgU(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I32AtomicRmw16XchgU(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64AtomicRmw8XchgU(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64AtomicRmw16XchgU(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64AtomicRmw32XchgU(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I32AtomicRmwCmpxchg(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64AtomicRmwCmpxchg(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I32AtomicRmw8CmpxchgU(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I32AtomicRmw16CmpxchgU(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64AtomicRmw8CmpxchgU(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64AtomicRmw16CmpxchgU(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::I64AtomicRmw32CmpxchgU(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::V128Load(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::V128Load8x8S(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::V128Load8x8U(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::V128Load16x4S(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::V128Load16x4U(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::V128Load32x2S(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::V128Load32x2U(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::V128Load8Splat(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::V128Load16Splat(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::V128Load32Splat(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::V128Load64Splat(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::V128Load32Zero(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::V128Load64Zero(memarg) => memarg.memory_index = 0,
        wasm_encoder::Instruction::V128Store(memarg) => memarg.memory_index = 0,
        _ => {}
    }
}