[package]
name = "atomic_wait_vfs"
authors.workspace = true
version.workspace = true
edition.workspace = true
description.workspace = true
license = "CC0-1.0"
rust-version.workspace = true
keywords.workspace = true
repository.workspace = true
documentation.workspace = true
homepage.workspace = true
readme.workspace = true
publish = false

[dependencies]
wit-bindgen = "0.54.0"
const_struct = "0.6.4"

[dependencies.wasi_virt_layer]
workspace = true
default-features = false
features = ["threads", "dynamic-fs"]

[lib]
crate-type = ["cdylib"]
