[package]
name = "wasip1_vfs-cli"
version = "0.1.0"
edition = "2024"
description = "CLI for the wasip1_vfs crate"
license = "MIT OR Apache-2.0"

[dependencies]
cargo_metadata = "0.19.2"
clap = { version = "4.5.36", features = ["derive"] }
console = "0.15.11"
js-component-bindgen = "1.10.0"
regex = "1.11.1"
serde_json = "1.0.140"
