[package]
name = "tmp_test_encoder"
authors.workspace = true
version.workspace = true
edition.workspace = true
description.workspace = true
rust-version.workspace = true
keywords.workspace = true
repository.workspace = true
documentation.workspace = true
homepage.workspace = true
readme.workspace = true

[dependencies]
wasm-encoder = "0.252.0"
