[package]
name = "example_vfs"
version.workspace = true
edition.workspace = true
publish=false

[dependencies]
wit-bindgen = "0.43.0"
const_struct = "0.6.2"
parking_lot = "0.12.3"

[dependencies.wasi_virt_layer]
workspace = true
features = ["std"]

[lib]
crate-type = ["cdylib"]
