[package]
name = "multiple-vfs"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
wit-bindgen = "0.54.0"
parking_lot = "0.12.3"
smallstr = "0.3.0"

[dependencies.wasi_virt_layer]
workspace = true
features = ["std", "alloc", "dynamic-fs", "multiple-fs", "trace-fs", "trace"]

[lib]
crate-type = ["cdylib"]
