// wit/wasip1_zero_layer.wit
// wit is only kebab-case
package wasip1-zero-layer:wasi;

world wasip1-zero-layer {
  resource zero-layer {
    fd-write-import: static func(fd: s32, iovs: s32, iovs-len: s32, written: s32) -> s32;
    environ-sizes-get-import: static func(environ-count: s32, environ-size: s32) -> s32;
    environ-get-import: static func(environ: s32, environ-buf: s32) -> s32;
    proc-exit-import: static func(code: s32);
  }
}
